### ISSUE TITLE
Getting array to string conversion

### ISSUE THREAD

**Issue by kotfarepra** [LeadSoftInc/cmb2-tabs#6]
Hi and thanks for the plugin 
Unfortunately i get an array to string conversion 

 Array to string conversion in /.../wp-content/plugins/test-tabs/vendor/cmb2/includes/types/CMB2_Type_Base.php on line 106

Seems on this filter 
$args = apply_filters( "cmb2_{$element}_attributes", $args, $type_defaults, $this->field, $this->types );

The {$element} is an array when i use the tabs 
Array ( [type] => post [id] => 613 [field_id] => __tabs [repeat] => [single] => 1 )

but for the usual "text" field its just the word "string" when i do a 
print_r($element);

**Comment by kotfarepra** [comment]
Did a bit of more testing and seems the issue is on 
cmb2-tabs.class.php on line 39 

the order of params needs to change to 
$default_data = $field_type_object->parse_args( 'tabs',$field_object->data_args(), array(

This for CMB 2.2.3.1

Regards

**Comment by mralessio** [comment]
I get the same issue..

**Comment by iSynthetica** [comment]
kotfarepra's fixing is working

**Comment by kuzmenko1256** [comment]
@kotfarepra 
What version of php do you use?
What parameters do you pass in the tabs field?

**Comment by kotfarepra** [comment]
Hi 
I dont have the files anymore but i used the default example i think  https://github.com/dThemeStudio/cmb2-tabs

Maybe try to ask @iSynthetica for the code since he has that working 

Regards

**Comment by kuzmenko1256** [comment]
@kotfarepra Thank you for your reply!
@iSynthetica I hope you can answer this question to me "What version of php do you use?What parameters do you pass in the tabs field?" :)

**Comment by vladislavl-hyuna** [comment]
@kuzmenko1256 
PHP ver is 5.6.3
i used it with example for Options page which CMB2 developers provided, but changed it a bit according to your example. All parameters the same as in your Option page example.

**Comment by kuzmenko1256** [comment]
Added support for CMB2 >= 2.2.2 #13
