### ISSUE TITLE
Saving empty fields on option page

### ISSUE THREAD

**Issue by vladislavl-hyuna** [LeadSoftInc/cmb2-tabs#8]
There is an issue while saving fields on option page. If you have some text field (for example) with some default value, or you enter some value into it and save options. After it was stored into DB, if you want to delete its value and save options, old value will remain, as far as there is no $_POST parameter for this field.

**Comment by glennlaysonjr** [comment]
I am having the same problem. I need to give my plugin over to my client next week and having this problem wont go over well with my client. Is there a fix yet?

**Comment by kuzmenko1256** [comment]
Fixed saving empty fields on option page #16
